runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.+)
  static_files: dist/factor-ds/\1
  upload: dist/factor-ds/(.*)

- url: /
  static_files: dist/factor-ds/index.html
  upload: dist/factor-ds/index.html

skip_files:
- e2e/
- node_modules/
- src/
- ^(.*/)?\..*$
- ^(.*/)?.*\.json$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yaml$
- ^Dockerfile
- ^LICENSE
