steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/yarn'
    args: [ '' ]

  # Build productive files
  - name: 'gcr.io/cloud-builders/yarn'
    args: [ 'build', '--configuration=production' ]

  # Deploy to google cloud app engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--version=1', '--project=github-builds-227920']
